"""background job queue

Revision ID: 00002f9f0461
Revises: 27d0756116a0
Create Date: 2026-07-28 08:59:42.528159+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

job_kind = postgresql.ENUM("ocr_document", name="job_kind", create_type=False)
job_status = postgresql.ENUM(
    "queued", "running", "succeeded", "failed", name="job_status", create_type=False
)
ALL_ENUMS = (job_kind, job_status)
revision: str = "00002f9f0461"
down_revision: str | None = "27d0756116a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for enum in ALL_ENUMS:
        enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("kind", job_kind, nullable=False),
        sa.Column("status", job_status, nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index("ix_job_status_run_after", "job", ["status", "run_after"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_status_run_after", table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
    for enum in reversed(ALL_ENUMS):
        enum.drop(op.get_bind(), checkfirst=True)
