"""passkey credentials

Revision ID: 27d0756116a0
Revises: be21fb82e87b
Create Date: 2026-07-28 08:52:31.142981+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "27d0756116a0"
down_revision: str | None = "be21fb82e87b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passkey",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_passkey_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkey")),
    )
    op.create_index("ix_passkey_credential_id", "passkey", ["credential_id"], unique=True)
    op.create_index(op.f("ix_passkey_user_id"), "passkey", ["user_id"], unique=False)
    op.create_table(
        "passkey_challenge",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("challenge", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_passkey_challenge_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkey_challenge")),
    )
    op.create_index(
        op.f("ix_passkey_challenge_user_id"), "passkey_challenge", ["user_id"], unique=False
    )
    op.create_index("ix_passkey_challenge_value", "passkey_challenge", ["challenge"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_passkey_challenge_value", table_name="passkey_challenge")
    op.drop_index(op.f("ix_passkey_challenge_user_id"), table_name="passkey_challenge")
    op.drop_table("passkey_challenge")
    op.drop_index(op.f("ix_passkey_user_id"), table_name="passkey")
    op.drop_index("ix_passkey_credential_id", table_name="passkey")
    op.drop_table("passkey")
    # ### end Alembic commands ###
