"""auth accounts sessions and audit

Revision ID: 6d9928f10001
Revises: c3f07a19b842
Create Date: 2026-07-28 00:50:45.816282+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

auth_event_type = postgresql.ENUM(
    "login_succeeded", "login_failed", name="auth_event_type", create_type=False
)
revision: str = "6d9928f10001"
down_revision: str | None = "c3f07a19b842"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    auth_event_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_event",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", auth_event_type, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_auth_event_user_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_event")),
    )
    op.create_index(
        "ix_auth_event_email_type_created",
        "auth_event",
        ["email", "event_type", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_auth_event_user_id"), "auth_event", ["user_id"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_digest", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_session_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
    )
    op.create_index(
        "ix_user_session_refresh_digest", "user_session", ["refresh_digest"], unique=True
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    op.create_table(
        "used_refresh_token",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user_session.id"],
            name=op.f("fk_used_refresh_token_session_id_user_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_used_refresh_token")),
    )
    op.create_index("ix_used_refresh_token_digest", "used_refresh_token", ["digest"], unique=True)
    op.create_index(
        op.f("ix_used_refresh_token_session_id"), "used_refresh_token", ["session_id"], unique=False
    )
    op.add_column("user_account", sa.Column("password_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "password_hash")
    op.drop_index(op.f("ix_used_refresh_token_session_id"), table_name="used_refresh_token")
    op.drop_index("ix_used_refresh_token_digest", table_name="used_refresh_token")
    op.drop_table("used_refresh_token")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index("ix_user_session_refresh_digest", table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_auth_event_user_id"), table_name="auth_event")
    op.drop_index("ix_auth_event_email_type_created", table_name="auth_event")
    op.drop_table("auth_event")
    # ### end Alembic commands ###
    auth_event_type.drop(op.get_bind(), checkfirst=True)
