"""case audit trail

Revision ID: be21fb82e87b
Revises: dc19afc76696
Create Date: 2026-07-28 08:49:02.292371+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

case_action = postgresql.ENUM(
    "case_created",
    "case_read",
    "case_list",
    "document_uploaded",
    "document_list",
    "document_read",
    name="case_action",
    create_type=False,
)
revision: str = "be21fb82e87b"
down_revision: str | None = "dc19afc76696"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    case_action.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_audit_event",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("action", case_action, nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user_account.id"],
            name=op.f("fk_case_audit_event_actor_user_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
            name=op.f("fk_case_audit_event_case_id_case"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_audit_event")),
    )
    op.create_index(
        op.f("ix_case_audit_event_actor_user_id"),
        "case_audit_event",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_case_audit_event_case_created",
        "case_audit_event",
        ["case_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_audit_event_case_id"), "case_audit_event", ["case_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_audit_event_case_id"), table_name="case_audit_event")
    op.drop_index("ix_case_audit_event_case_created", table_name="case_audit_event")
    op.drop_index(op.f("ix_case_audit_event_actor_user_id"), table_name="case_audit_event")
    op.drop_table("case_audit_event")
    # ### end Alembic commands ###
    case_action.drop(op.get_bind(), checkfirst=True)
