"""mfa enrolment and recovery codes

Revision ID: dc19afc76696
Revises: 6d9928f10001
Create Date: 2026-07-28 08:39:54.321781+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc19afc76696"
down_revision: str | None = "6d9928f10001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recovery_code",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_recovery_code_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_code")),
    )
    op.create_index(
        "ix_recovery_code_user_digest", "recovery_code", ["user_id", "digest"], unique=True
    )
    op.create_table(
        "user_mfa",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_secret", sa.String(length=500), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_counter", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_mfa_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_mfa")),
    )
    op.create_index("ix_user_mfa_user_id", "user_mfa", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_mfa_user_id", table_name="user_mfa")
    op.drop_table("user_mfa")
    op.drop_index("ix_recovery_code_user_digest", table_name="recovery_code")
    op.drop_table("recovery_code")
    # ### end Alembic commands ###
